cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      auto: false
      static: ${AWS_REGION}
    sqs:
      url: ${AWS_SQS_URL}
    stack:
      auto: false

spring:
  profiles:
    active: local