cloud:
  aws:
    credentials:
      access-key: <HERE_GOES_YOUR_ACCESS_KEY>
      secret-key: <HERE_GOES_YOUR_SECRET_KEY>
    region:
      auto: false
      static: sa-east-1
    sqs:
      url: <HERE_GOES_THE_QUEUE_URL>
    stack:
      auto: false

spring:
  profiles:
    active: local